create extension if not exists pgcrypto;
create type public.user_role as enum ('user','admin');
create type public.request_status as enum ('pending','approved','rejected');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null, name text, role public.user_role not null default 'user',
  status text not null default 'فعال', created_at timestamptz not null default now()
);
create table public.books (
  id uuid primary key default gen_random_uuid(), title text not null, title_en text,
  author text not null, translator text, description text not null default '',
  page_count integer not null default 1, language text not null default 'فارسی',
  category text not null default 'عمومی', price bigint not null default 0,
  cover_palette jsonb not null default '["#1f3a2e","#0f2419"]',
  cover_url text, published boolean not null default false,
  created_at timestamptz not null default now()
);
create table public.book_pages (
  id bigint generated by default as identity primary key, book_id uuid not null references public.books on delete cascade,
  page_number integer not null, image_path text not null, unique(book_id,page_number)
);
create table public.purchase_requests (
  id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references public.profiles on delete cascade,
  book_id uuid not null references public.books on delete cascade, receipt_reference text,
  status public.request_status not null default 'pending', created_at timestamptz not null default now(), approved_at timestamptz
);
create table public.entitlements (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade,
  book_id uuid not null references public.books on delete cascade, purchase_request_id uuid references public.purchase_requests,
  created_at timestamptz not null default now(), unique(user_id,book_id)
);
create table public.reading_progress (
  user_id uuid not null references public.profiles on delete cascade, book_id uuid not null references public.books on delete cascade,
  page_number integer not null default 1, updated_at timestamptz not null default now(), primary key(user_id,book_id)
);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin insert into public.profiles(id,email,name) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'name',split_part(new.email,'@',1))); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from profiles where id=auth.uid() and role='admin'); $$;

alter table public.profiles enable row level security; alter table public.books enable row level security;
alter table public.book_pages enable row level security; alter table public.purchase_requests enable row level security;
alter table public.entitlements enable row level security; alter table public.reading_progress enable row level security;
create policy "profiles own or admin" on profiles for select using(id=auth.uid() or is_admin());
create policy "admin profiles" on profiles for update using(is_admin());
create policy "published books" on books for select using(published or is_admin());
create policy "admin books" on books for all using(is_admin()) with check(is_admin());
create policy "pages entitled" on book_pages for select using(is_admin() or exists(select 1 from entitlements e where e.book_id=book_pages.book_id and e.user_id=auth.uid()));
create policy "admin pages" on book_pages for all using(is_admin()) with check(is_admin());
create policy "requests own read" on purchase_requests for select using(user_id=auth.uid() or is_admin());
create policy "requests own create" on purchase_requests for insert with check(user_id=auth.uid());
create policy "requests admin update" on purchase_requests for update using(is_admin());
create policy "entitlements own read" on entitlements for select using(user_id=auth.uid() or is_admin());
create policy "entitlements admin" on entitlements for all using(is_admin()) with check(is_admin());
create policy "progress own" on reading_progress for all using(user_id=auth.uid()) with check(user_id=auth.uid());
insert into storage.buckets(id,name,public) values('book-pages','book-pages',false),('book-covers','book-covers',true) on conflict do nothing;
create policy "admins upload pages" on storage.objects for insert with check(bucket_id in ('book-pages','book-covers') and public.is_admin());
create policy "admins update assets" on storage.objects for update using(public.is_admin());
create policy "entitled page files" on storage.objects for select using(bucket_id='book-pages' and (public.is_admin() or exists(select 1 from public.book_pages p join public.entitlements e on e.book_id=p.book_id where p.image_path=name and e.user_id=auth.uid())));
create policy "public covers" on storage.objects for select using(bucket_id='book-covers');
