interface Env{DB:D1Database;JWT_SECRET:string;ADMIN_EMAIL:string}
const enc=new TextEncoder();
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Authorization, Content-Type","Access-Control-Allow-Methods":"GET,POST,PATCH,DELETE,OPTIONS"};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{...cors,"Content-Type":"application/json; charset=utf-8"}});
const b64=(bytes:Uint8Array)=>btoa(String.fromCharCode(...bytes)).replace(/=/g,"").replace(/\+/g,"-").replace(/\//g,"_");
const unb64=(s:string)=>Uint8Array.from(atob(s.replace(/-/g,"+").replace(/_/g,"/")),c=>c.charCodeAt(0));
async function hmac(data:string,secret:string){const key=await crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign","verify"]);return new Uint8Array(await crypto.subtle.sign("HMAC",key,enc.encode(data)));}
async function token(user:any,env:Env){const head=b64(enc.encode(JSON.stringify({alg:"HS256",typ:"JWT"}))),body=b64(enc.encode(JSON.stringify({sub:user.id,email:user.email,role:user.role,exp:Math.floor(Date.now()/1000)+604800}))),data=`${head}.${body}`;return`${data}.${b64(await hmac(data,env.JWT_SECRET))}`;}
async function auth(req:Request,env:Env){try{const raw=req.headers.get("Authorization")?.replace(/^Bearer /,"");if(!raw)return null;const[a,b,s]=raw.split("."),data=`${a}.${b}`,expected=await hmac(data,env.JWT_SECRET),actual=unb64(s);let ok=actual.length===expected.length;for(let i=0;i<actual.length&&ok;i++)ok=actual[i]===expected[i];if(!ok)return null;const payload=JSON.parse(new TextDecoder().decode(unb64(b)));if(payload.exp<Date.now()/1000)return null;return payload;}catch{return null;}}
async function hashPassword(password:string,salt?:string){const s=salt?unb64(salt):crypto.getRandomValues(new Uint8Array(16)),key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]),bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:s,iterations:120000,hash:"SHA-256"},key,256);return{hash:b64(new Uint8Array(bits)),salt:b64(s)};}
const id=()=>crypto.randomUUID();
function book(r:any){return{id:r.id,title:r.title,titleEn:r.title_en,author:r.author,translator:r.translator,description:r.description,pageCount:r.page_count,language:r.language,category:r.category,price:r.price,coverUrl:r.cover_url,published:Boolean(r.published)};}
async function body(req:Request){return req.json() as Promise<any>;}

export default{async fetch(req:Request,env:Env){try{if(req.method==="OPTIONS")return new Response(null,{headers:cors});const u=new URL(req.url),p=u.pathname,user=await auth(req,env);
  if(p==="/health")return json({ok:true});
  if(p==="/auth/signup"&&req.method==="POST"){const x=await body(req);if(!x.email||!x.password||x.password.length<8)return json({message:"رمز عبور باید حداقل ۸ کاراکتر باشد."},400);const email=String(x.email).trim().toLowerCase(),hp=await hashPassword(x.password),role=email===env.ADMIN_EMAIL.toLowerCase()?"admin":"reader",uid=id();try{await env.DB.prepare("INSERT INTO users(id,email,name,password_hash,password_salt,role) VALUES(?,?,?,?,?,?)").bind(uid,email,x.name||email,hp.hash,hp.salt,role).run();}catch{return json({message:"این ایمیل قبلاً ثبت شده است."},409);}const usr={id:uid,email,role};return json({access_token:await token(usr,env),refresh_token:"",user:usr},201);}
  if(p==="/auth/login"&&req.method==="POST"){const x=await body(req),r=await env.DB.prepare("SELECT * FROM users WHERE email=?").bind(String(x.email||"").trim().toLowerCase()).first<any>();if(!r)return json({message:"ایمیل یا رمز عبور اشتباه است."},401);const hp=await hashPassword(x.password,r.password_salt);if(hp.hash!==r.password_hash)return json({message:"ایمیل یا رمز عبور اشتباه است."},401);const usr={id:r.id,email:r.email,role:r.role};return json({access_token:await token(usr,env),refresh_token:"",user:usr});}
  if(p==="/me"){if(!user)return json({message:"ابتدا وارد شوید."},401);const r=await env.DB.prepare("SELECT id,name,email,status,role FROM users WHERE id=?").bind(user.sub).first<any>();return json({...r,assignedBookIds:[]});}
  if(p==="/books"&&req.method==="GET"){const admin=u.searchParams.get("admin")==="1"&&user?.role==="admin",q=admin?"SELECT * FROM books ORDER BY created_at DESC":"SELECT * FROM books WHERE published=1 ORDER BY created_at DESC",rs=await env.DB.prepare(q).all<any>();return json(rs.results.map(book));}
  if(p==="/books"&&req.method==="POST"){if(user?.role!=="admin")return json({message:"دسترسی مدیر لازم است."},403);const x=await body(req),bid=id();await env.DB.prepare("INSERT INTO books(id,title,title_en,author,translator,description,page_count,language,category,price,cover_url,published) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").bind(bid,x.title,x.titleEn||null,x.author,x.translator||null,x.description||"",x.pageCount||1,x.language||"فارسی",x.category||"عمومی",x.price||0,x.coverUrl||null,x.published===false?0:1).run();return json({id:bid,...x},201);}
  const bm=p.match(/^\/books\/([^/]+)$/);if(bm&&req.method==="PATCH"){if(user?.role!=="admin")return json({message:"دسترسی مدیر لازم است."},403);const x=await body(req);await env.DB.prepare("UPDATE books SET title=?,title_en=?,author=?,translator=?,description=?,page_count=?,language=?,category=?,price=?,cover_url=?,published=? WHERE id=?").bind(x.title,x.titleEn||null,x.author,x.translator||null,x.description||"",x.pageCount||1,x.language||"فارسی",x.category||"عمومی",x.price||0,x.coverUrl||null,x.published===false?0:1,bm[1]).run();return json({id:bm[1],...x});}
  if(bm&&req.method==="DELETE"){if(user?.role!=="admin")return json({message:"دسترسی مدیر لازم است."},403);await env.DB.prepare("DELETE FROM books WHERE id=?").bind(bm[1]).run();return json({ok:true});}
  if(p==="/users"){if(user?.role!=="admin")return json({message:"دسترسی مدیر لازم است."},403);const rs=await env.DB.prepare("SELECT id,name,email,status,role FROM users ORDER BY created_at DESC").all<any>();return json(rs.results.map(r=>({...r,assignedBookIds:[]})));}
  if(p==="/purchase-requests"&&req.method==="GET"){if(user?.role!=="admin")return json({message:"دسترسی مدیر لازم است."},403);const rs=await env.DB.prepare("SELECT pr.*,u.name,u.email,b.title FROM purchase_requests pr JOIN users u ON u.id=pr.user_id JOIN books b ON b.id=pr.book_id ORDER BY pr.created_at DESC").all<any>();return json(rs.results.map(r=>({...r,profiles:{name:r.name,email:r.email},books:{title:r.title}})));}
  if(p==="/purchase-requests"&&req.method==="POST"){if(!user)return json({message:"ابتدا وارد شوید."},401);const x=await body(req),rid=id();await env.DB.prepare("INSERT INTO purchase_requests(id,user_id,book_id,receipt_reference) VALUES(?,?,?,?)").bind(rid,user.sub,x.book_id,x.receipt_reference||"").run();return json([{id:rid,user_id:user.sub,book_id:x.book_id,status:"pending",receipt_reference:x.receipt_reference,created_at:new Date().toISOString()}],201);}
  const ap=p.match(/^\/purchase-requests\/([^/]+)\/approve$/);if(ap&&req.method==="POST"){if(user?.role!=="admin")return json({message:"دسترسی مدیر لازم است."},403);const r=await env.DB.prepare("SELECT * FROM purchase_requests WHERE id=?").bind(ap[1]).first<any>();if(!r)return json({message:"درخواست پیدا نشد."},404);await env.DB.batch([env.DB.prepare("UPDATE purchase_requests SET status='approved',approved_at=CURRENT_TIMESTAMP WHERE id=?").bind(ap[1]),env.DB.prepare("INSERT OR IGNORE INTO entitlements(id,user_id,book_id,purchase_request_id) VALUES(?,?,?,?)").bind(id(),r.user_id,r.book_id,r.id)]);return json({ok:true});}
  const ent=p.match(/^\/entitlements\/([^/]+)$/);if(ent){if(!user)return json({allowed:false});if(user.role==="admin")return json({allowed:true});const r=await env.DB.prepare("SELECT id FROM entitlements WHERE user_id=? AND book_id=?").bind(user.sub,ent[1]).first();return json({allowed:Boolean(r)});}
  if(p==="/my-books"){if(!user)return json({message:"ابتدا وارد شوید."},401);const rs=await env.DB.prepare("SELECT b.* FROM books b JOIN entitlements e ON e.book_id=b.id WHERE e.user_id=?").bind(user.sub).all<any>();return json(rs.results.map(book));}
  if(p==="/uploads"&&req.method==="POST"){if(user?.role!=="admin")return json({message:"دسترسی مدیر لازم است."},403);const f=await req.formData(),file=f.get("file") as File;if(!file||file.size>1900000)return json({message:"حجم هر تصویر باید کمتر از ۱.۹ مگابایت باشد."},400);const kind=String(f.get("kind")),bid=String(f.get("book_id")),page=Number(f.get("page")||0),key=`${kind}s/${bid}/${id()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`,bytes=await file.arrayBuffer();await env.DB.prepare("INSERT INTO files(object_key,content_type,data) VALUES(?,?,?)").bind(key,file.type||"application/octet-stream",bytes).run();if(kind==="page")await env.DB.prepare("INSERT OR REPLACE INTO book_pages(id,book_id,page_number,object_key) VALUES(?,?,?,?)").bind(id(),bid,page,key).run();const origin=new URL(req.url).origin;return json({url:`${origin}/files/${encodeURIComponent(key)}`});}
  const pages=p.match(/^\/books\/([^/]+)\/pages$/);if(pages&&req.method==="DELETE"){if(user?.role!=="admin")return json({message:"دسترسی مدیر لازم است."},403);await env.DB.prepare("DELETE FROM book_pages WHERE book_id=?").bind(pages[1]).run();return json({ok:true});}
  if(pages&&req.method==="GET"){if(!user)return json({message:"ابتدا وارد شوید."},401);if(user.role!=="admin"){const e=await env.DB.prepare("SELECT id FROM entitlements WHERE user_id=? AND book_id=?").bind(user.sub,pages[1]).first();if(!e)return json({message:"این کتاب برای شما فعال نشده است."},403);}const rs=await env.DB.prepare("SELECT object_key FROM book_pages WHERE book_id=? ORDER BY page_number").bind(pages[1]).all<any>(),origin=new URL(req.url).origin;return json(rs.results.map(r=>`${origin}/files/${encodeURIComponent(r.object_key)}?token=${encodeURIComponent(req.headers.get("Authorization")?.slice(7)||"")}`));}
  if(p.startsWith("/files/")){const key=decodeURIComponent(p.slice(7)),cover=key.startsWith("covers/"),qtoken=u.searchParams.get("token"),viewer=cover?user:await auth(new Request(req.url,{headers:{Authorization:`Bearer ${qtoken||""}`}}),env);if(!cover&&!viewer)return json({message:"دسترسی مجاز نیست."},401);const obj=await env.DB.prepare("SELECT content_type,data FROM files WHERE object_key=?").bind(key).first<any>();if(!obj)return new Response("Not found",{status:404,headers:cors});return new Response(obj.data,{headers:{...cors,"Content-Type":obj.content_type||"application/octet-stream","Cache-Control":cover?"public, max-age=86400":"private, no-store","Content-Disposition":"inline"}});}
  return json({message:"مسیر پیدا نشد."},404);
}catch(e){console.error(e);return json({message:"خطای داخلی سرور"},500);}}};
